// client-vue3/src/components/Advertisement.vue
<template>
	<v-card class="mx-auto" max-width="344">
		<v-card-subtitle>
			<small>{{ details.category }} </small>
		</v-card-subtitle>

		<v-card-title>
			{{ details.title }}
		</v-card-title>

		<v-card-subtitle>
			<small>
				<i
					>By {{ details.createdByUserName }} | At {{ details.updatedOn }}</i
				></small
			>
		</v-card-subtitle>

		<v-img v-if="details.image" :src="details.image" height="200px"></v-img>

		<v-card-text>
			{{ details.description }}
		</v-card-text>

		<v-card-actions v-if="details.isEditEnable">
			<v-btn variant="outlined" color="primary">
				EDIT
			</v-btn>
			<v-btn variant="outlined" color="error" @click="remove">
				REMOVE
			</v-btn>
		</v-card-actions>
	</v-card></template
>

<script>
export default { name: "Advertisement", props: ["details"] };
</script>

<style scoped></style>

// client-app/src/app/advertisement/advertisement.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { AdvertisementModel } from '../models/advertisementModel';

@Component({
  selector: 'advertisement-card',
  templateUrl: './advertisement.component.html',
  styleUrls: ['./advertisement.component.css']
})
export class AdvertisementComponent implements OnInit {

  @Input()
  advertisement!: AdvertisementModel;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="content">
    <mat-card class="mat-elevation-z4">
        <mat-card-header>
            <mat-card-subtitle>
                <small [class]="categoryClass">{{advertisement.category}} </small>
                <hr>
            </mat-card-subtitle>
            <mat-card-title>{{advertisement.title}}</mat-card-title>
            <mat-card-subtitle>
                <small>
                    <i>By {{advertisement.createdByUserName}} | At {{advertisement.updatedOn |
                        date:'medium'}}</i></small>
            </mat-card-subtitle>
        </mat-card-header>
        <img *ngIf="!!advertisement.image" mat-card-image [src]="advertisement.image" alt="Image Of Advertisement">
        <mat-card-content>
            <p>{{advertisement.description}}</p>
        </mat-card-content>
        <mat-card-actions *ngIf="advertisement.isEditEnable">
            <button mat-button mat-stroked-button color="primary" (click)="update()">EDIT</button>
            <button mat-button mat-stroked-button color="warn" (click)="delete()">REMOVE</button>
        </mat-card-actions>
    </mat-card>
</div>
